/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.HashMap;

class MainTest {
    HashMap<String, Integer> testMenu = new HashMap<String, Integer>();
    public void fillUpList(){
        testMenu.put("Pizza", 11);
        testMenu.put("Pasta", 8);
        testMenu.put("Burger", 14);
        testMenu.put("Steak", 12);
    }

    @Test void testDisplayMenu(){
        fillUpList(); //@BeforeAll did not work so I am taking the easy way out
        //Menu menu = mock(Menu.class);
        //when(menu.list()).thenReturn([{"Pizza" = Integer.valueOf(11)}]);

        Main main = new Main();
        //assertEquals("---------\nOur menu:\n1. Pizza - 11£\n2. Burger - 8£\n3. Steak - 14£\n4. Pasta - 12£\n---------", main.displayMenu(testMenu));
    }

    @AfterAll
    public void emptyList(HashMap<String, Integer> testMenu){
        testMenu.clear();
    }
}
