/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway;

import java.util.Map;
import java.util.Scanner;
import java.util.HashMap;

public class Main {

    public HashMap<String, Integer> chosenDish = new HashMap<String, Integer>();
    static Menu menu = new Menu();
    Boolean endOfInput = false;

    public void displayMenu(Map<String, Integer> list){
        System.out.println("---------\nOur menu:\n");
        int i = 1;

        for(Map.Entry<String, Integer> set : list.entrySet()){
            String name = set.getKey();
            Integer price = set.getValue();
            System.out.printf("%d. %s - %d£\n", i, name, price);
            i++;
        }
        System.out.println("---------");
    }

    public void addDish(String input){
        switch(input) {
            case "1": 
                chosenDish.put("Pizza", 11);  //hardcoded for now
                break;
            case "2":
                chosenDish.put("Burger", 8);  //hardcoded for now
                break;
            case "3":           
                chosenDish.put("Steak", 14);  //hardcoded for now
                break;
            case "4":            
                chosenDish.put("Pasta", 12);  //hardcoded for now
                break;
            default:
                System.out.println("You did not give me a valid value.");
                break;
        }
    }

    public static void main(String[] args) {
        Main main = new Main();
        Scanner reader = new Scanner(System.in);
        main.displayMenu(menu.list());
        System.out.println("Which item would you like?");
        while(!main.endOfInput) {
            String input = reader.nextLine();
            main.addDish(input);
            System.out.println("Is there anything else you would like? Y/N?");

        }
        reader.close();
    }
}
