/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway;

public class Main {

    public static void main(String[] args) {
        OrderCli cli = new OrderCli();
        cli.call();
    }
}
